-- This is an empty migration.
ALTER SEQUENCE "PromoProduct_id_seq" MINVALUE 1 START 11 RESTART 11;
ALTER SEQUENCE "Category_id_seq" MINVALUE 1 START 11 RESTART 11;
ALTER SEQUENCE "Product_id_seq" RESTART WITH 21;