ALTER SEQUENCE "User_id_seq" RESTART WITH 5;
ALTER SEQUENCE "AffiliateCode_id_seq" RESTART WITH 5;
ALTER SEQUENCE "Cart_id_seq" RESTART WITH 5;


ALTER SEQUENCE "PromoProduct_id_seq" RESTART WITH 20;
